### ISSUE TITLE
Figure out how to use Kubernetes with playlist service

### ISSUE THREAD

**Issue by KamiCreed** [scp756-221/term-project-k8sound#25]
Can use minikube to test.

**Comment by de2008de** [comment]
Successfully start minikube on my Windows WSL by following the documentation on README. Will see how do we deploy the three services and add the steps to the documentation.

**Comment by haoyup** [comment]
> Successfully start minikube on my Windows WSL by following the documentation on README. Will see how do we deploy the three services and add the steps to the documentation.

You can run the command from k8s.mak file. The command to build and deploy s2, db, and gw are listed below for your convenience:
`
# Build all images
make -f k8s.mak cri
`
`
# Deploy
make -f k8s.mak gw s2 db
`

**Comment by de2008de** [comment]
> > Successfully start minikube on my Windows WSL by following the documentation on README. Will see how do we deploy the three services and add the steps to the documentation.
> 
> You can run the command from k8s.mak file. The command to build and deploy s2, db, and gw are listed below for your convenience: build all images: `make -f k8s.mak cri` Deploy: `make -f k8s.mak gw s2 db`

Thank you, David. I will add s3 to k8s.mak as well.
