### ISSUE TITLE
Look into Grafana, Prometheus, and Istio documentation

### ISSUE THREAD

**Issue by KamiCreed** [scp756-221/term-project-k8sound#30]
Everyone should probably look into this.

**Comment by de2008de** [comment]
Went through Guide 1—Grafana and successfully start a cluster with gatling sending requests. The Grafana dashboard shows the metrics.
Will go through Guide 2 - Metrics and Prometheus shortly.

**Comment by de2008de** [comment]
Finished all three guides. I highly recommend everyone try these three guides to have a general idea how we can evaluate our system performance.

**Comment by de2008de** [comment]
I will outline some ideas to evaluate our system performance on the interim report.
